color = input("Enter your color: ")
plural_noun = input("Enter your plural_noun: ")
person = input("Enter your person: ")
print("Roses are " + color)
print(plural_noun + " are blue")
print("I love "+person)
